name: .NET

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Pack
      run: dotnet pack ./Sixpence.ORM/Sixpence.ORM.csproj -c Release /p:Version=${VERSION} -o -IncludeReferencedProjects .
    - name: Publish
      run: dotnet nuget push Sixpence.ORM.${VERSION}.nupkg -k ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
